[package]
authors = [
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
  "Timothée Delabrouille <https://github.com/tdelabro>",
]
description = "Starknet RPC compatibility layer for Substrate"
edition.workspace = true
homepage = "https://github.com/keep-starknet-strange/madara"
license = "MIT"
name = "mc-rpc"
publish = false
repository = "https://github.com/keep-starknet-strange/madara"
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Madara utils
mc-genesis-data-provider = { workspace = true }

# Madara runtime
deoxys-runtime = { workspace = true }
pallet-starknet = { workspace = true, default-features = true }
pallet-starknet-runtime-api = { workspace = true, default-features = true }

# Madara client
mc-db = { workspace = true }
mc-storage = { workspace = true }
mc-sync = { workspace = true }

# Substate primitives
sc-transaction-pool = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sp-api = { workspace = true, default-features = true }
sp-arithmetic = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
# Substrate client
sc-client-api = { workspace = true, default-features = true }
sc-network-sync = { workspace = true }
# Starknet
blockifier = { workspace = true, default-features = true }
starknet-core = { workspace = true }
starknet-ff = { workspace = true }
starknet-providers = { workspace = true }
starknet_api = { workspace = true, default-features = true }
# Others
anyhow = { workspace = true }
cairo-lang-casm-contract-class = { workspace = true }
flate2 = { workspace = true }
hex = { workspace = true, default-features = true }
indexmap = { workspace = true, default-features = true }
itertools = { workspace = true }
jsonrpsee = { workspace = true, default-features = true, features = [
  "macros",
  "server",
] }
log = { workspace = true, default-features = true }
mp-block = { workspace = true, default-features = true }
mp-contract = { workspace = true, default-features = true }
mp-convert = { workspace = true, default-features = true }
mp-digest-log = { workspace = true }
mp-fee = { workspace = true, default-features = true }
mp-felt = { workspace = true, default-features = true }
mp-hashers = { workspace = true, default-features = true }
mp-simulations = { workspace = true }
mp-transactions = { workspace = true, features = ["client"] }
mp-types = { workspace = true }
num-bigint = { workspace = true }
serde = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
bitvec = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
