[package]
authors = ["Antiyro <https://github.com/antiyro>"]
description = "Deoxys crate for Madara"
edition = "2021"
homepage = "https://github.com/KasarLabs/deoxys"
license = "MIT"
name = "mc-sync"
publish = false
repository = "https://github.com/KasarLabs/deoxys"
version = "0.1.0"

[features]
default = ["m"]
m = ["dep:rodio"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
anyhow = "1.0.75"
ethers = { workspace = true }
lazy_static = { workspace = true }
reqwest = { workspace = true }
serde_json = "1"


blockifier = { workspace = true, default-features = false, features = [
  "testing",
] }
futures = { workspace = true, default-features = true }
hex = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
primitive-types = { workspace = true }
rand = { workspace = true }
rodio = { version = "0.17", optional = true }
serde = { workspace = true, default-features = true }
tokio = { workspace = true, features = ["macros", "parking_lot", "test-util"] }
url = { workspace = true }

deoxys-runtime = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
starknet-core = { workspace = true }
starknet-ff = { workspace = true, default-features = false, features = [
  "alloc",
  "serde",
] }
starknet-providers = { workspace = true }
starknet_api = { workspace = true, default-features = false }

sc-consensus-manual-seal.workspace = true
sp-blockchain = { workspace = true, default-features = true }
sp-core = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true }

bitvec = { workspace = true }
bonsai-trie = { workspace = true }
mc-db = { workspace = true }
mc-storage = { workspace = true }
mp-block = { workspace = true }
mp-contract = { workspace = true }
mp-fee = { workspace = true }
mp-felt = { workspace = true }
mp-hashers = { workspace = true }
mp-storage = { workspace = true, default-features = true }
mp-transactions = { workspace = true, features = ["client"] }
mp-types = { workspace = true }
starknet-types-core = { workspace = true, default-features = false, features = [
  "hash",
  "parity-scale-codec",
] }
thiserror.workspace = true

[dev-dependencies]
# test_utils = { path = "./test_utils" }
